website/music/urls.py
from django.conf.urls import url
from . import views

app_name='music'
urlpatterns = [
    #  /music/
    url(r'^$',views.IndexView.as_view(), name = "index"),

    # /register/
    url(r'^register/$',views.UserFormView.as_view(), name = "register"),

    # /music/342
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name ='details'),

    #/music/album/add

    url(r'^album/add/$', views.CreateAlbum.as_view(), name ='album-add'),

    #/music/album/2

    url(r'^album/(?P<pk>[0-9]+)/$', views.UpdateAlbum.as_view(), name ='album-update'),

    #/music/album/2/delete

    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.DeleteAlbum.as_view(), name ='album-delete'),

]

website/website/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from companies import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^stocks/', views.StockList.as_view()),
]

urlpatterns=format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/companies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Stock(models.Model):
    ticker=models.CharField(max_length=10)
    open=models.FloatField()
    close=models.FloatField()
    volume=models.IntegerField()

    def __str__(self):
        return self.ticker

website/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title=models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo=models.FileField()

    def get_absolute_url(self):
        return reverse('music:details',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=100)
    is_favorite=models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

website/companies/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Stock
from serializer import StockSerializer


from django.shortcuts import render

# Create your views here.

class StockList(APIView):
    def get(self,request):
        stocks = Stock.objects.all()
        serializer = StockSerializer(stocks,many=True)
        return Response(serializer.data)

website/music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm
from django.views.generic import View


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name= 'album_list'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

class CreateAlbum(CreateView):
    model = Album
    fields=['artist', 'album_title', 'genre' , 'album_logo']

class UpdateAlbum(UpdateView):
    model = Album
    fields=['artist', 'album_title', 'genre' , 'album_logo']

class DeleteAlbum(DeleteView):
    model = Album
    success_url =  reverse_lazy('music:index')

class UserFormView(View):
    form_class=UserForm
    template_name='music/registration_form.html'

    #display blank form
    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    #process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)

        #cleaned(normalized) data
            username =form.cleaned_data['username']
            password =form.cleaned_data['password']
            user.set_password(password)
            user.save()

        #return user objects if credentials are correct

            user=authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request,self.template_name,{'form':form})

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block body %}

<form class="form-horizontal" action="" method="GET" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'music/form_template.html' %}
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-default">Submit</button>
          </div>
      </div>
</form>

{% endblock %}

website/music/templates/music/base.html
<html>
<head>
    <title>{% block title %} Vito {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <!-- Logo -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#demo">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'music:index'%}">VitoParker</a>
      </div>

      <!-- Menu items -->
      <div class="collapse navbar-collapse" id="demo">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'music:index'%}">
            <span class="glyphicon glyphicon-cd "></span>&nbsp;Albums</a>
          </li>
          <li><a href="{% url 'music:index'%}">
            <span class="glyphicon glyphicon-music"></span>&nbsp;Songs</a>
          </li>

        </ul>



    <form class="navbar-form navbar-left" role="search" method="get" action="#">
      <div class="form-group">
        <input type="text" class="form-control" name="q" value="">
      </div>
        <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'music:album-add' %}">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;Add Albums</a>
          </li>
          <li><a href="#">
            <span class="glyphicon glyphicon-off"></span>&nbsp;Logout</a>
          </li>
        </ul>

      </div>
      </div>
    </nav>


{% block body %}
{% endblock %}

</body>

</html>

website/music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %} Song Details {% endblock %}

{% block body %}

  <img src="{{album.album_logo.url}}">

  <h2>{{ album.album_title}}</h2>
  <h3>{{ album.artist }}</h3>

  {% if error_message %}
    <p> <strong> {{error_message}} </strong> </p>
  {% endif %}


  <form >
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{forloop.counter}}" name='song' value="{{song.id}}">
      <label> {{song.song_title}} </label><br>
      {% if song.is_favorite %}
        <img src="http://i.imgur.com/b9b13Rd.png" />
      {% endif %}
      </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
  </form>
{% endblock %}

website/music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}
{% block body %}

  <!-- <div class="row">
    <div class="col-md-4"><img src="\static\music\images\Desert.jpg" class="img-thumbnail" alt="Cinque Terre" width="304" height="236">
  </div>

    <div class="col-md-4">
  <img src="\static\music\images\Desert.jpg" class="img-thumbnail" alt="Cinque Terre" width="304" height="236">
    </div> -->
      <div class="row">
    {% for album in album_list %}

        <div class="col-md-4">
          <img src="{{album.album_logo.url}}" class="img-thumbnail" width="304" height="236">

            <br><h5 ><b>&nbsp;&nbsp;&nbsp;{{ album.album_title}} - {{ album.artist }}</b></h5>
            <div class="btn">
              <a href="{% url 'music:album-update' album.id %}" class="btn btn-primary">View Details</a>
             <form method="POST" action="{% url 'music:album-delete' album.id %}">
               {% csrf_token %}<input type="submit" value="DELETE">
            </form>﻿

            </div>



        </div>

        {% if error_message %}
          <p><strong>{{error_message}}</strong></p>
        {% endif %}

    {% endfor %}
      </div>




  <!-- {% for album in album_list %}
      <h5 class="col-md-4"><b>{{ album.album_title}} - {{ album.artist }}</b></h5>


      {% if error_message %}
        <p><strong>{{error_message}}</p></strong>
      {% endif %}
  {% endfor %}
</div> -->

<!-- {% if object_list %}
    <h2 > These are my albums </h2>
    <ul>
      {% for album in album_list %}
      <li> <a href= "{% url 'music:details' album.id %}"> {{album.album_title}} </a> </li>
      {% endfor %}
    </ul>

{% else %}
  <h2> There are no albums present </h2>

{% endif %} -->

{% endblock %}

website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block body %}

<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'music/form_template.html' %}
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-default">Submit</button>
          </div>
      </div>
</form>

{% endblock %}